# Generated by Django 4.2.1 on 2025-05-04 08:48

from django.db import migrations, models
import files.models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0003_file_reference_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.FileField(null=True, upload_to=files.models.file_upload_path),
        ),
        migrations.AlterField(
            model_name='file',
            name='file_type',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='file',
            name='size',
            field=models.BigIntegerField(null=True),
        ),
    ]
