# Generated by Django 4.2.1 on 2025-05-07 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0004_alter_file_file_alter_file_file_type_alter_file_size'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='file',
            index=models.Index(fields=['file_type'], name='files_file_file_ty_2d7e73_idx'),
        ),
        migrations.AddIndex(
            model_name='file',
            index=models.Index(fields=['size'], name='files_file_size_6009e9_idx'),
        ),
        migrations.AddIndex(
            model_name='file',
            index=models.Index(fields=['uploaded_at'], name='files_file_uploade_726d10_idx'),
        ),
        migrations.AddIndex(
            model_name='file',
            index=models.Index(fields=['reference_id'], name='files_file_referen_3cb547_idx'),
        ),
        migrations.AddIndex(
            model_name='file',
            index=models.Index(fields=['original_filename'], name='files_file_origina_63129f_idx'),
        ),
    ]
