# Generated by Django 4.2.1 on 2025-05-07 17:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0005_file_files_file_file_ty_2d7e73_idx_and_more'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='file',
            new_name='files_file_referen_410472_idx',
            old_name='files_file_referen_3cb547_idx',
        ),
        migrations.AlterField(
            model_name='file',
            name='reference_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referenced_by', to='files.file'),
        ),
    ]
