# Generated by Django 4.2.1 on 2025-05-07 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0006_rename_files_file_referen_3cb547_idx_files_file_referen_410472_idx_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='file',
            old_name='reference_id',
            new_name='reference',
        ),
        migrations.RenameIndex(
            model_name='file',
            new_name='files_file_referen_3cb547_idx',
            old_name='files_file_referen_410472_idx',
        ),
    ]
